### ISSUE TITLE
Визуальное восприятие.

### ISSUE THREAD

**Issue by makedonen** [alexey-svistunov/tm_googlemap#2]
Столкнулись с проблемой правильной настройки карты. У сборщика не отображалась карта из-за того, что он не ввёл все значения во все поля.
Необходимо либо выставить дефолтные значения в поля, либо сделать пометку обязательного поля для заполнения.

Возле поля, со вставкой стилей, необходимо сделать приписку и указать, что стили можно взять с snazzymaps.com.

Желательно в описании на репозитории указать, как вставить карту на главной странице не только после футера, а и перед футером или в самом футере, в блоке шириной, к примеру, 4 грида.

**Comment by alexey-svistunov** [comment]
fixed
изменен способ вывода contact page map. 
Всё описано в readme
